<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>I See You Detector AI</Title>
    <Authors>SunnymoonSoftwares</Authors>
    <Product>$(Authors)-$(AssemblyName)</Product>
    <Description>Yolo engine that get persons and objects to a frame display.</Description>
    <Copyright>SunnymoonSoftwares</Copyright>
    <PackageIcon>Logo_800x800.png</PackageIcon>
    <RepositoryUrl>https://github.com/luanparedes/ISeeYou</RepositoryUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\ISeeYou\ISeeYou\Assets\Logo_800x800.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Emgu.CV" Version="4.12.0.5764" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.12.0.5764" />
  </ItemGroup>

</Project>
